name: insta_personal_page_lego
description: "beautiful insta personal page lego"
#publish_to: 'none'
repository: https://github.com/flutter-lego/insta_personal_page_lego

version: 1.0.3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  gap: #@add
  flutter_svg: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/lego/insta_personal_page_lego/
  uses-material-design: true

topics:
  - lego